###user  eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNDg1NzYsImV4cCI6MjkzNDIyNzk0MDg3MjgzMiwic3ViIjoidXNlciJ9.HR8NdjUEzLW59On4y1DEVo_gEBc5j105aoVCwIEfmsY
###admin eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNDg1NTcsImV4cCI6MjkzNDIyNzkwNzQ3OTIzMiwic3ViIjoiYWRtaW4ifQ.HwvcmMy_RgG1Mhsix9GC5WDCMJ-BP1h41Dcf5chMl0Y

POST localhost:8080/user
Content-Type: application/json

{
  "username": "admin",
  "password": "123456789"

}

###

POST localhost:8080/user
Content-Type: application/json

{
  "username": "user",
  "password": "123456789"

}

###

POST localhost:8080/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456789"
}

###

PUT localhost:8080/makeadmin/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTYxNjQsImV4cCI6MjkzNDI0MTA1MTQ1NTkzNiwic3ViIjoiYWRtaW4ifQ.rDfYgXR1vgxYlmaoC7Z_DaU7dtqlezPjBLn0cNckY78

{
  "admin": true
}
###

POST localhost:8080/user/login
Content-Type: application/json

{
  "username": "user",
  "password": "12345678"
}
###

POST localhost:8080/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTY2MTksImV4cCI6MjkzNDI0MTgzODUzNTc0NCwic3ViIjoiYWRtaW4ifQ.suqBCLb1vXqRSM8-HDLoC_gBg98Dqt8Q2PdzQqJ3vy0

{

  "active": 1,
  "name": "test2"

}

###

POST localhost:8080/product/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTg0MTY3NjcsImV4cCI6MjkzNDg2NDE3NTAxMjQxNiwic3ViIjoiYWRtaW4ifQ.Xo1Ja0ejuxriJpNZDoxVpiClt5Gr4QCniguZOGels_I

{
  "active": 1,
  "name": "To Be Deleted",
  "stock": 10,
  "sku": "55",
  "price": 99999999999,
  "description": "this is a new product"
}

###

GET localhost:8080/product
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTYyMjIsImV4cCI6MjkzNDI0MTE1MTk4MDYwOCwic3ViIjoidXNlcjIifQ.GiY5fEVgv4ePr4QylYcc0CjmxO2WVNGyOKIBKlk9F60

###

GET localhost:8080/product/5
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTYyMjIsImV4cCI6MjkzNDI0MTE1MTk4MDYwOCwic3ViIjoidXNlcjIifQ.GiY5fEVgv4ePr4QylYcc0CjmxO2WVNGyOKIBKlk9F60

###
PUT localhost:8080/product/2
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTY2MTksImV4cCI6MjkzNDI0MTgzODUzNTc0NCwic3ViIjoiYWRtaW4ifQ.suqBCLb1vXqRSM8-HDLoC_gBg98Dqt8Q2PdzQqJ3vy0

{
  "active": 0,
  "name": "renamed product",
  "stock": 100,
  "sku": "1",
  "price": 20,
  "description": "this product was renamed"
}

###

DELETE localhost:8080/product/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTg0MTY3NjcsImV4cCI6MjkzNDg2NDE3NTAxMjQxNiwic3ViIjoiYWRtaW4ifQ.Xo1Ja0ejuxriJpNZDoxVpiClt5Gr4QCniguZOGels_I

###


GET localhost:8080/user/1

###

GET localhost:8080/user

###

PUT localhost:8080/user/1
Content-Type: application/json

{
  "username": "changedUser",
  "password": "aqbcdefg",
  "admin": true
}

###
DELETE localhost:8080/user/1

###
POST localhost:8080/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTU3OTIsImV4cCI6MjkzNDI0MDQwODcxMDc4NCwic3ViIjoiYWRtaW4ifQ.vJURmzX3jHZlpQmUDHt0oE2qSKv9yTG8fypiX1s6C4I

{

  "active": 1,
  "name": "test2"

}

###
GET localhost:8080/category/1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTY2MTksImV4cCI6MjkzNDI0MTgzODUzNTc0NCwic3ViIjoiYWRtaW4ifQ.suqBCLb1vXqRSM8-HDLoC_gBg98Dqt8Q2PdzQqJ3vy0

###
GET localhost:8080/category
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTY2MTksImV4cCI6MjkzNDI0MTgzODUzNTc0NCwic3ViIjoiYWRtaW4ifQ.suqBCLb1vXqRSM8-HDLoC_gBg98Dqt8Q2PdzQqJ3vy0

###

PUT localhost:8080/category/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTY2MTksImV4cCI6MjkzNDI0MTgzODUzNTc0NCwic3ViIjoiYWRtaW4ifQ.suqBCLb1vXqRSM8-HDLoC_gBg98Dqt8Q2PdzQqJ3vy0

{
  "name": "neuer cooler Name",
  "active": 1

}

###

GET localhost:8080/category/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTY2MTksImV4cCI6MjkzNDI0MTgzODUzNTc0NCwic3ViIjoiYWRtaW4ifQ.suqBCLb1vXqRSM8-HDLoC_gBg98Dqt8Q2PdzQqJ3vy0

###

DELETE localhost:8080/category/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTY2MTksImV4cCI6MjkzNDI0MTgzODUzNTc0NCwic3ViIjoiYWRtaW4ifQ.suqBCLb1vXqRSM8-HDLoC_gBg98Dqt8Q2PdzQqJ3vy0

###
GET http://localhost:8080/swagger-ui/index.html