###user  eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNDg1NzYsImV4cCI6MjkzNDIyNzk0MDg3MjgzMiwic3ViIjoidXNlciJ9.HR8NdjUEzLW59On4y1DEVo_gEBc5j105aoVCwIEfmsY
###admin eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNDg1NTcsImV4cCI6MjkzNDIyNzkwNzQ3OTIzMiwic3ViIjoiYWRtaW4ifQ.HwvcmMy_RgG1Mhsix9GC5WDCMJ-BP1h41Dcf5chMl0Y

POST localhost:8080/user
Content-Type: application/json

{
  "username": "admin",
  "password": "123456789"

}

###

POST localhost:8080/user
Content-Type: application/json

{
  "username": "user2",
  "password": "123456789"

}

###

POST localhost:8080/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456789"
}

###

PUT localhost:8080/makeadmin/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTMyNDcsImV4cCI6MjkzNDIzNjAxMTUxOTI5Niwic3ViIjoiYWRtaW4ifQ.UHvvhTkdEKBCU3vBhSOyEPl0-RHb0xR5Du8jxtEq8rY

{
  "admin": true
}
###

POST localhost:8080/user/login
Content-Type: application/json

{
  "username": "user2",
  "password": "123456789"
}
###

POST localhost:8080/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTE0OTUsImV4cCI6MjkzNDIzMjk4NDAyMzU1Miwic3ViIjoiYWRtaW4ifQ.ql83isURIf-GB3gKw5K5irLl3KRWTZ-UlIYn-rdblv8

{

  "active": 1,
  "name": "test1"

}

###

POST localhost:8080/product/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNTE0OTUsImV4cCI6MjkzNDIzMjk4NDAyMzU1Miwic3ViIjoiYWRtaW4ifQ.ql83isURIf-GB3gKw5K5irLl3KRWTZ-UlIYn-rdblv8

{
  "active": 1,
  "name": "test product 2 posted",
  "stock": 10,
  "sku": "55",
  "price": 99999999999,
  "description": "this is a new product"
}

###

GET localhost:8080/product
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNDg1NTcsImV4cCI6MjkzNDIyNzkwNzQ3OTIzMiwic3ViIjoiYWRtaW4ifQ.HwvcmMy_RgG1Mhsix9GC5WDCMJ-BP1h41Dcf5chMl0Y

###

GET localhost:8080/product/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNDg1NTcsImV4cCI6MjkzNDIyNzkwNzQ3OTIzMiwic3ViIjoiYWRtaW4ifQ.HwvcmMy_RgG1Mhsix9GC5WDCMJ-BP1h41Dcf5chMl0Y

###
PUT localhost:8080/product/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNDg1NTcsImV4cCI6MjkzNDIyNzkwNzQ3OTIzMiwic3ViIjoiYWRtaW4ifQ.HwvcmMy_RgG1Mhsix9GC5WDCMJ-BP1h41Dcf5chMl0Y

{
  "active": 0,
  "name": "renamed product",
  "stock": 100,
  "sku": "1",
  "price": 20,
  "description": "this product was renamed"
}

###

DELETE localhost:8080/product/1

###


GET localhost:8080/user/1

###

GET localhost:8080/user

###

PUT localhost:8080/user/1
Content-Type: application/json

{
  "username": "changedUser",
  "password": "aqbcdefg",
  "admin": true
}

###
DELETE localhost:8080/user/1

###
POST localhost:8080/category
Content-Type: application/json

{

  "active": 1,
  "name": "test2"

}

###
GET localhost:8080/category/1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNDg1NTcsImV4cCI6MjkzNDIyNzkwNzQ3OTIzMiwic3ViIjoiYWRtaW4ifQ.HwvcmMy_RgG1Mhsix9GC5WDCMJ-BP1h41Dcf5chMl0Y

###
GET localhost:8080/category
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNDg1NTcsImV4cCI6MjkzNDIyNzkwNzQ3OTIzMiwic3ViIjoiYWRtaW4ifQ.HwvcmMy_RgG1Mhsix9GC5WDCMJ-BP1h41Dcf5chMl0Y

###

PUT localhost:8080/category/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCcmVjaHQiLCJpYXQiOjE2OTgwNDg1NTcsImV4cCI6MjkzNDIyNzkwNzQ3OTIzMiwic3ViIjoiYWRtaW4ifQ.HwvcmMy_RgG1Mhsix9GC5WDCMJ-BP1h41Dcf5chMl0Y

{
  "name": "neuer cooler Name",
  "active": 1

}



